### ISSUE TITLE
spotify connector is no longer sending data (last entry 11-29)

### ISSUE THREAD

**Issue by woolfg** [openpodcast/roadmap#70]
graph generate on 2022-12-02 contains only data until 11-28

![Image](https://user-images.githubusercontent.com/1328269/205400098-3442e696-9d25-42e4-8cab-a83f3c4278d2.png)

**Comment by woolfg** [comment]
is there a prob with the connector @mre

**Comment by woolfg** [comment]
Spotify connector seems to be not working anymore

`select * from spotifyEpisodeDetailedStreams order by sps_date DESC LIMIT 5;`

```
account_id | episode_id | sps_date | sps_starts | sps_streams
-- | -- | -- | -- | --
1 | 12B15FQ84hAfopW5d8AJPA | 2022-11-29 | 0 | 0
1 | 2ebg5MhyOK9rotpCBfe830 | 2022-11-29 | 0 | 0
1 | 08VSwqmWlk8DgknnmwYxK0 | 2022-11-29 | 0 | 0
1 | 1dwB3ztpzOOIfIh6hVYr6t | 2022-11-29 | 0 | 0
2 | 7xXnR8rP8gB25P9dQkvVQk | 2022-11-29 | 0 | 0
```

**Comment by mre** [comment]
Looks like I messed up:

```python
2022-12-06 11:10:05.273 | SUCCESS  | spotifyconnector.connector:_authenticate:161 - *** retrieved!
Traceback (most recent call last):
  File "/home/runner/work/open/open/spotify/main.py", line 245, in <module>
    main()
  File "/home/runner/work/open/open/spotify/main.py", line 109, in main
    fetch_and_capture(
  File "/home/runner/work/open/open/spotify/main.py", line 74, in fetch_and_capture
    result = open_podcast_client.capture(
  File "/home/runner/work/open/open/spotify/main.py", line 42, in capture
    return requests.post(self.endpoint, headers=headers, json=json)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?
Error: Process completed with exit code 1.
```

https://github.com/openpodcast/open/actions/runs/3628963848/jobs/6120608208

I think it's because the api endpoint does not get passed properly in the pipeline; sorry.
Let me look into that.

**Comment by mre** [comment]
Testing in https://github.com/openpodcast/open/actions/runs/3629312691

**Comment by mre** [comment]
Yup, I forgot to pass the [new endpoint environment variable](https://github.com/openpodcast/open/commit/27113025eb736541d6efd4b050be4cd444299ffb). 🤦
